M48
; DRILL file KiCad 10.0.0 date 2026-03-25T13:21:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-25T13:21:58+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X78.3Y-64.785
X78.3Y-70.565
T2
X101.2Y-46.5
X109.6Y-46.5
X109.6Y-131.67
M30
