#ifndef CAMERA_BOARD_CONFIG_H
#define CAMERA_BOARD_CONFIG_H

/* Camera sequencing  */
#define CAMERA_BOARD_CAMERA_BOOT_DELAY_MS          5000U
#define CAMERA_BOARD_RECORD_DURATION_MS            10000U
#define CAMERA_BOARD_POST_STOP_POWER_OFF_DELAY_MS  10000U

/* Camera UART  */
#define CAMERA_BOARD_CAMERA_UART_BAUD_RATE         115200U
#define CAMERA_BOARD_CAMERA_UART_TX_TIMEOUT_MS     50U

/* Debug/output UART  */
#define CAMERA_BOARD_OUTPUT_UART_TX_TIMEOUT_MS     50U

/* Power behavior  */
#define CAMERA_BOARD_POWER_OFF_AFTER_RECORDING     0U

#endif /* CAMERA_BOARD_CONFIG_H */
